version: "3.9"

services:
  api:
    container_name: express_api
    image: api_entrega
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_USER=felip
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB=products_management
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: database
    image: postgres:12
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=felip
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U felip -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
